### ISSUE TITLE
Not clean if this generator can generate modules.

### ISSUE THREAD

**Issue by qwiglydee** [FountainJS/fountain#44]
#### Configuration

Wish to scaffold angular1 reusable modules. 
Or modules + demo application.
#### Version

0.6.0
#### Expected and current behaviors

Expected something like `fountain-angular1-module`. 
Available generators can only generate single application module and add components to it.

**Comment by micaelmbagira** [comment]
No, this generator cannot generate AngularJS modules, if you need to know more about FountainJS sub-generator here is some reading https://github.com/FountainJS/generator-fountain-angular1#sub-generators ;)
