### ISSUE TITLE
Add a new integration test for livereloading for JS & CSS

### ISSUE THREAD

**Issue by Swiip** [FountainJS/fountain#5]
It should be possible to have a test which modify a file and wait for the modification to be present on the browser.

It won't be easy to setup but it could be really awesome.

**Comment by zckrs** [comment]
@micaelmbagira what are your concern about this? Possible or not?

**Comment by micaelmbagira** [comment]
I already worked on this one but couldn't make the test stable so the code is there but disabled. Plus, the test took very long (>1 hour)

**Comment by Swiip** [comment]
Yep, not possible with the test environment we've got today (Travis & Saucelabs on OSS plans).
