### ISSUE TITLE
New readme summing up all build status and other badges

### ISSUE THREAD

**Issue by Swiip** [FountainJS/fountain#8]
Even if we'll keep basics badges on each repo, I'd like to use this readme to gather all badges on the projet. Especially the travis ones with on top the integration tests status but also each badges on the builds on each repositories.

As for having a big dashboard, why not putting here all the badges we could think of.

**Comment by zckrs** [comment]
https://github.com/FountainJS/fountain#submodules-status

Do you want add more badges ?

**Comment by Swiip** [comment]
I would have loved a badge per integration test combination but it's really hard to make. When we divided integration test with as many Travis build instances as configurations, I imagined that as possible, but now, it seems not unless by parsing Travis build logs.
